version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    environment:
      - SECRET=myverysecretpassword1234567890
      - DATABASE_URL=mysql://root:123456@host.docker.internal:3306/database
      - SHADOW_DATABASE_URL=mysql://root:123456@host.docker.internal:3306/database_shadow
    ports:
      - 3000:3000
volumes:
  mysqldb:
